# Generated by juwelier
^ Style/FrozenStringLiteralComment: Missing frozen string literal comment.
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "glimmer-dsl-swt".freeze
end
