pub mod assignment_in_condition;
pub mod boolean_symbol;
pub mod debugger;
pub mod deprecated_class_methods;
pub mod duplicate_branch;
pub mod duplicate_case_condition;
pub mod duplicate_elsif_condition;
pub mod duplicate_hash_key;
pub mod duplicate_magic_comment;
pub mod duplicate_methods;
pub mod duplicate_require;
pub mod duplicate_rescue_exception;
pub mod each_with_object_argument;
pub mod else_layout;
pub mod empty_block;
pub mod empty_class;
pub mod empty_conditional_body;
pub mod empty_ensure;
pub mod empty_expression;
pub mod empty_interpolation;
pub mod empty_when;
pub mod ensure_return;
pub mod float_out_of_range;
pub mod identity_comparison;
pub mod interpolation_check;
pub mod literal_as_condition;
pub mod literal_in_interpolation;
pub mod loop_cop;
pub mod nested_method_definition;
pub mod non_local_exit_from_iterator;
pub mod or_assignment_to_constant;
pub mod raise_exception;
pub mod redundant_safe_navigation;
pub mod redundant_string_coercion;
pub mod redundant_with_index;
pub mod redundant_with_object;
pub mod require_parentheses;
pub mod rescue_exception;
pub mod return_in_void_context;
pub mod safe_navigation_chain;
pub mod self_assignment;
pub mod shadowed_argument;
pub mod suppressed_exception;
pub mod symbol_conversion;
pub mod triple_quotes;
pub mod unified_integer;
pub mod unreachable_code;
pub mod unused_block_argument;
pub mod unused_method_argument;
pub mod uri_escape_unescape;
pub mod uri_regexp;
pub mod useless_method_definition;
pub mod void;

use super::registry::CopRegistry;

pub fn register_all(registry: &mut CopRegistry) {
    registry.register(Box::new(assignment_in_condition::AssignmentInCondition));
    registry.register(Box::new(boolean_symbol::BooleanSymbol));
    registry.register(Box::new(debugger::Debugger));
    registry.register(Box::new(deprecated_class_methods::DeprecatedClassMethods));
    registry.register(Box::new(duplicate_branch::DuplicateBranch));
    registry.register(Box::new(duplicate_case_condition::DuplicateCaseCondition));
    registry.register(Box::new(duplicate_elsif_condition::DuplicateElsifCondition));
    registry.register(Box::new(duplicate_hash_key::DuplicateHashKey));
    registry.register(Box::new(duplicate_magic_comment::DuplicateMagicComment));
    registry.register(Box::new(duplicate_methods::DuplicateMethods));
    registry.register(Box::new(duplicate_require::DuplicateRequire));
    registry.register(Box::new(duplicate_rescue_exception::DuplicateRescueException));
    registry.register(Box::new(each_with_object_argument::EachWithObjectArgument));
    registry.register(Box::new(else_layout::ElseLayout));
    registry.register(Box::new(empty_block::EmptyBlock));
    registry.register(Box::new(empty_class::EmptyClass));
    registry.register(Box::new(empty_conditional_body::EmptyConditionalBody));
    registry.register(Box::new(empty_ensure::EmptyEnsure));
    registry.register(Box::new(empty_expression::EmptyExpression));
    registry.register(Box::new(empty_interpolation::EmptyInterpolation));
    registry.register(Box::new(empty_when::EmptyWhen));
    registry.register(Box::new(ensure_return::EnsureReturn));
    registry.register(Box::new(float_out_of_range::FloatOutOfRange));
    registry.register(Box::new(identity_comparison::IdentityComparison));
    registry.register(Box::new(interpolation_check::InterpolationCheck));
    registry.register(Box::new(literal_as_condition::LiteralAsCondition));
    registry.register(Box::new(literal_in_interpolation::LiteralInInterpolation));
    registry.register(Box::new(loop_cop::Loop));
    registry.register(Box::new(nested_method_definition::NestedMethodDefinition));
    registry.register(Box::new(non_local_exit_from_iterator::NonLocalExitFromIterator));
    registry.register(Box::new(or_assignment_to_constant::OrAssignmentToConstant));
    registry.register(Box::new(raise_exception::RaiseException));
    registry.register(Box::new(redundant_safe_navigation::RedundantSafeNavigation));
    registry.register(Box::new(redundant_string_coercion::RedundantStringCoercion));
    registry.register(Box::new(redundant_with_index::RedundantWithIndex));
    registry.register(Box::new(redundant_with_object::RedundantWithObject));
    registry.register(Box::new(require_parentheses::RequireParentheses));
    registry.register(Box::new(rescue_exception::RescueException));
    registry.register(Box::new(return_in_void_context::ReturnInVoidContext));
    registry.register(Box::new(safe_navigation_chain::SafeNavigationChain));
    registry.register(Box::new(self_assignment::SelfAssignment));
    registry.register(Box::new(shadowed_argument::ShadowedArgument));
    registry.register(Box::new(suppressed_exception::SuppressedException));
    registry.register(Box::new(symbol_conversion::SymbolConversion));
    registry.register(Box::new(triple_quotes::TripleQuotes));
    registry.register(Box::new(unified_integer::UnifiedInteger));
    registry.register(Box::new(unreachable_code::UnreachableCode));
    registry.register(Box::new(unused_block_argument::UnusedBlockArgument));
    registry.register(Box::new(unused_method_argument::UnusedMethodArgument));
    registry.register(Box::new(uri_escape_unescape::UriEscapeUnescape));
    registry.register(Box::new(uri_regexp::UriRegexp));
    registry.register(Box::new(useless_method_definition::UselessMethodDefinition));
    registry.register(Box::new(void::Void));
}
