pub mod action_controller_flash_before_render;
pub mod action_controller_test_case;
pub mod action_filter;
pub mod action_order;
pub mod active_record_aliases;
pub mod active_record_callbacks_order;
pub mod active_record_override;
pub mod active_support_aliases;
pub mod active_support_on_load;
pub mod add_column_index;
pub mod after_commit_override;
pub mod application_controller;
pub mod application_job;
pub mod application_mailer;
pub mod application_record;
pub mod arel_star;
pub mod assert_not;
pub mod attribute_default_block_value;
pub mod belongs_to;
pub mod blank;
pub mod bulk_change_table;
pub mod compact_blank;
pub mod content_tag;
pub mod create_table_with_timestamps;
pub mod dangerous_column_names;
pub mod date;
pub mod default_scope;
pub mod delegate;
pub mod delegate_allow_blank;
pub mod deprecated_active_model_errors_methods;
pub mod dot_separated_keys;
pub mod duplicate_association;
pub mod duplicate_scope;
pub mod duration_arithmetic;
pub mod dynamic_find_by;
pub mod eager_evaluation_log_message;
pub mod enum_hash;
pub mod enum_syntax;
pub mod enum_uniqueness;
pub mod env;
pub mod env_local;
pub mod environment_comparison;
pub mod environment_variable_access;
pub mod exit;
pub mod expanded_date_range;
pub mod file_path;
pub mod find_by;
pub mod find_by_id;
pub mod find_by_or_assignment_memoization;
pub mod find_each;
pub mod freeze_time;
pub mod has_and_belongs_to_many;
pub mod has_many_or_has_one_dependent;
pub mod helper_instance_variable;
pub mod http_positional_arguments;
pub mod http_status;
pub mod http_status_name_consistency;
pub mod i18n_lazy_lookup;
pub mod i18n_locale_assignment;
pub mod i18n_locale_texts;
pub mod ignored_columns_assignment;
pub mod ignored_skip_action_filter_option;
pub mod index_by;
pub mod index_with;
pub mod inquiry;
pub mod inverse_of;
pub mod lexically_scoped_action_filter;
pub mod link_to_blank;
pub mod mailer_name;
pub mod match_route;
pub mod migration_class_name;
pub mod multiple_route_paths;
pub mod negate_include;
pub mod not_null_column;
pub mod order_arguments;
pub mod order_by_id;
pub mod output;
pub mod output_safety;
pub mod pick;
pub mod pluck;
pub mod pluck_id;
pub mod pluck_in_where;
pub mod pluralization_grammar;
pub mod presence;
pub mod present;
pub mod rake_environment;
pub mod read_write_attribute;
pub mod redirect_back_or_to;
pub mod redundant_active_record_all_method;
pub mod redundant_allow_nil;
pub mod redundant_foreign_key;
pub mod redundant_presence_validation_on_belongs_to;
pub mod redundant_receiver_in_with_options;
pub mod redundant_travel_back;
pub mod reflection_class_name;
pub mod refute_methods;
pub mod relative_date_constant;
pub mod render_inline;
pub mod render_plain_text;
pub mod request_referer;
pub mod require_dependency;
pub mod response_parsed_body;
pub mod reversible_migration;
pub mod reversible_migration_method_definition;
pub mod root_join_chain;
pub mod root_pathname_methods;
pub mod root_public_path;
pub mod safe_navigation;
pub mod safe_navigation_with_blank;
pub mod save_bang;
pub mod schema_comment;
pub mod scope_args;
pub mod select_map;
pub mod short_i18n;
pub mod skips_model_validations;
pub mod squished_sql_heredocs;
pub mod strip_heredoc;
pub mod strong_parameters_expect;
pub mod table_name_assignment;
pub mod three_state_boolean_column;
pub mod time_zone;
pub mod time_zone_assignment;
pub mod to_formatted_s;
pub mod to_s_with_argument;
pub mod top_level_hash_with_indifferent_access;
pub mod transaction_exit_statement;
pub mod uniq_before_pluck;
pub mod unique_validation_without_index;
pub mod unknown_env;
pub mod unused_ignored_columns;
pub mod unused_render_content;
pub mod validation;
pub mod where_equals;
pub mod where_exists;
pub mod where_not;
pub mod where_missing;
pub mod where_not_with_multiple_conditions;
pub mod where_range;

use super::registry::CopRegistry;

pub fn register_all(registry: &mut CopRegistry) {
    registry.register(Box::new(action_controller_flash_before_render::ActionControllerFlashBeforeRender));
    registry.register(Box::new(action_controller_test_case::ActionControllerTestCase));
    registry.register(Box::new(action_filter::ActionFilter));
    registry.register(Box::new(action_order::ActionOrder));
    registry.register(Box::new(active_record_aliases::ActiveRecordAliases));
    registry.register(Box::new(active_record_callbacks_order::ActiveRecordCallbacksOrder));
    registry.register(Box::new(active_record_override::ActiveRecordOverride));
    registry.register(Box::new(active_support_aliases::ActiveSupportAliases));
    registry.register(Box::new(active_support_on_load::ActiveSupportOnLoad));
    registry.register(Box::new(add_column_index::AddColumnIndex));
    registry.register(Box::new(after_commit_override::AfterCommitOverride));
    registry.register(Box::new(application_controller::ApplicationController));
    registry.register(Box::new(application_job::ApplicationJob));
    registry.register(Box::new(application_mailer::ApplicationMailer));
    registry.register(Box::new(application_record::ApplicationRecord));
    registry.register(Box::new(arel_star::ArelStar));
    registry.register(Box::new(assert_not::AssertNot));
    registry.register(Box::new(attribute_default_block_value::AttributeDefaultBlockValue));
    registry.register(Box::new(belongs_to::BelongsTo));
    registry.register(Box::new(blank::Blank));
    registry.register(Box::new(bulk_change_table::BulkChangeTable));
    registry.register(Box::new(compact_blank::CompactBlank));
    registry.register(Box::new(content_tag::ContentTag));
    registry.register(Box::new(create_table_with_timestamps::CreateTableWithTimestamps));
    registry.register(Box::new(dangerous_column_names::DangerousColumnNames));
    registry.register(Box::new(date::Date));
    registry.register(Box::new(default_scope::DefaultScope));
    registry.register(Box::new(delegate::Delegate));
    registry.register(Box::new(delegate_allow_blank::DelegateAllowBlank));
    registry.register(Box::new(deprecated_active_model_errors_methods::DeprecatedActiveModelErrorsMethods));
    registry.register(Box::new(dot_separated_keys::DotSeparatedKeys));
    registry.register(Box::new(duplicate_association::DuplicateAssociation));
    registry.register(Box::new(duplicate_scope::DuplicateScope));
    registry.register(Box::new(duration_arithmetic::DurationArithmetic));
    registry.register(Box::new(dynamic_find_by::DynamicFindBy));
    registry.register(Box::new(eager_evaluation_log_message::EagerEvaluationLogMessage));
    registry.register(Box::new(enum_hash::EnumHash));
    registry.register(Box::new(enum_syntax::EnumSyntax));
    registry.register(Box::new(enum_uniqueness::EnumUniqueness));
    registry.register(Box::new(env::Env));
    registry.register(Box::new(env_local::EnvLocal));
    registry.register(Box::new(environment_comparison::EnvironmentComparison));
    registry.register(Box::new(environment_variable_access::EnvironmentVariableAccess));
    registry.register(Box::new(exit::Exit));
    registry.register(Box::new(expanded_date_range::ExpandedDateRange));
    registry.register(Box::new(file_path::FilePath));
    registry.register(Box::new(find_by::FindBy));
    registry.register(Box::new(find_by_id::FindById));
    registry.register(Box::new(find_by_or_assignment_memoization::FindByOrAssignmentMemoization));
    registry.register(Box::new(find_each::FindEach));
    registry.register(Box::new(freeze_time::FreezeTime));
    registry.register(Box::new(has_and_belongs_to_many::HasAndBelongsToMany));
    registry.register(Box::new(has_many_or_has_one_dependent::HasManyOrHasOneDependent));
    registry.register(Box::new(helper_instance_variable::HelperInstanceVariable));
    registry.register(Box::new(http_positional_arguments::HttpPositionalArguments));
    registry.register(Box::new(http_status::HttpStatus));
    registry.register(Box::new(http_status_name_consistency::HttpStatusNameConsistency));
    registry.register(Box::new(i18n_lazy_lookup::I18nLazyLookup));
    registry.register(Box::new(i18n_locale_assignment::I18nLocaleAssignment));
    registry.register(Box::new(i18n_locale_texts::I18nLocaleTexts));
    registry.register(Box::new(ignored_columns_assignment::IgnoredColumnsAssignment));
    registry.register(Box::new(ignored_skip_action_filter_option::IgnoredSkipActionFilterOption));
    registry.register(Box::new(index_by::IndexBy));
    registry.register(Box::new(index_with::IndexWith));
    registry.register(Box::new(inquiry::Inquiry));
    registry.register(Box::new(inverse_of::InverseOf));
    registry.register(Box::new(lexically_scoped_action_filter::LexicallyScopedActionFilter));
    registry.register(Box::new(link_to_blank::LinkToBlank));
    registry.register(Box::new(mailer_name::MailerName));
    registry.register(Box::new(match_route::MatchRoute));
    registry.register(Box::new(migration_class_name::MigrationClassName));
    registry.register(Box::new(multiple_route_paths::MultipleRoutePaths));
    registry.register(Box::new(negate_include::NegateInclude));
    registry.register(Box::new(not_null_column::NotNullColumn));
    registry.register(Box::new(order_arguments::OrderArguments));
    registry.register(Box::new(order_by_id::OrderById));
    registry.register(Box::new(output::Output));
    registry.register(Box::new(output_safety::OutputSafety));
    registry.register(Box::new(pick::Pick));
    registry.register(Box::new(pluck::Pluck));
    registry.register(Box::new(pluck_id::PluckId));
    registry.register(Box::new(pluck_in_where::PluckInWhere));
    registry.register(Box::new(pluralization_grammar::PluralizationGrammar));
    registry.register(Box::new(presence::Presence));
    registry.register(Box::new(present::Present));
    registry.register(Box::new(rake_environment::RakeEnvironment));
    registry.register(Box::new(read_write_attribute::ReadWriteAttribute));
    registry.register(Box::new(redirect_back_or_to::RedirectBackOrTo));
    registry.register(Box::new(redundant_active_record_all_method::RedundantActiveRecordAllMethod));
    registry.register(Box::new(redundant_allow_nil::RedundantAllowNil));
    registry.register(Box::new(redundant_foreign_key::RedundantForeignKey));
    registry.register(Box::new(redundant_presence_validation_on_belongs_to::RedundantPresenceValidationOnBelongsTo));
    registry.register(Box::new(redundant_receiver_in_with_options::RedundantReceiverInWithOptions));
    registry.register(Box::new(redundant_travel_back::RedundantTravelBack));
    registry.register(Box::new(reflection_class_name::ReflectionClassName));
    registry.register(Box::new(refute_methods::RefuteMethods));
    registry.register(Box::new(relative_date_constant::RelativeDateConstant));
    registry.register(Box::new(render_inline::RenderInline));
    registry.register(Box::new(render_plain_text::RenderPlainText));
    registry.register(Box::new(request_referer::RequestReferer));
    registry.register(Box::new(require_dependency::RequireDependency));
    registry.register(Box::new(response_parsed_body::ResponseParsedBody));
    registry.register(Box::new(reversible_migration::ReversibleMigration));
    registry.register(Box::new(reversible_migration_method_definition::ReversibleMigrationMethodDefinition));
    registry.register(Box::new(root_join_chain::RootJoinChain));
    registry.register(Box::new(root_pathname_methods::RootPathnameMethods));
    registry.register(Box::new(root_public_path::RootPublicPath));
    registry.register(Box::new(safe_navigation::SafeNavigation));
    registry.register(Box::new(safe_navigation_with_blank::SafeNavigationWithBlank));
    registry.register(Box::new(save_bang::SaveBang));
    registry.register(Box::new(schema_comment::SchemaComment));
    registry.register(Box::new(scope_args::ScopeArgs));
    registry.register(Box::new(select_map::SelectMap));
    registry.register(Box::new(short_i18n::ShortI18n));
    registry.register(Box::new(skips_model_validations::SkipsModelValidations));
    registry.register(Box::new(squished_sql_heredocs::SquishedSQLHeredocs));
    registry.register(Box::new(strip_heredoc::StripHeredoc));
    registry.register(Box::new(strong_parameters_expect::StrongParametersExpect));
    registry.register(Box::new(table_name_assignment::TableNameAssignment));
    registry.register(Box::new(three_state_boolean_column::ThreeStateBooleanColumn));
    registry.register(Box::new(time_zone::TimeZone));
    registry.register(Box::new(time_zone_assignment::TimeZoneAssignment));
    registry.register(Box::new(to_formatted_s::ToFormattedS));
    registry.register(Box::new(to_s_with_argument::ToSWithArgument));
    registry.register(Box::new(top_level_hash_with_indifferent_access::TopLevelHashWithIndifferentAccess));
    registry.register(Box::new(transaction_exit_statement::TransactionExitStatement));
    registry.register(Box::new(uniq_before_pluck::UniqBeforePluck));
    registry.register(Box::new(unique_validation_without_index::UniqueValidationWithoutIndex));
    registry.register(Box::new(unknown_env::UnknownEnv));
    registry.register(Box::new(unused_ignored_columns::UnusedIgnoredColumns));
    registry.register(Box::new(unused_render_content::UnusedRenderContent));
    registry.register(Box::new(validation::Validation));
    registry.register(Box::new(where_equals::WhereEquals));
    registry.register(Box::new(where_exists::WhereExists));
    registry.register(Box::new(where_not::WhereNot));
    registry.register(Box::new(where_missing::WhereMissing));
    registry.register(Box::new(where_not_with_multiple_conditions::WhereNotWithMultipleConditions));
    registry.register(Box::new(where_range::WhereRange));
}
