#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate bench/results.md from hyperfine JSON and conformance JSON.
# Usage: report.rb [--output bench/results.md]
#
# Reads from bench/results/:
#   *-bench.json        — hyperfine benchmark results
#   *-conformance.json  — conformance comparison results
#   covered-cops.txt    — list of turbocop cops

require "json"
require "time"

SCRIPT_DIR = File.expand_path(__dir__)
RESULTS_DIR = File.join(SCRIPT_DIR, "results")
DEFAULT_OUTPUT = File.join(SCRIPT_DIR, "results.md")

output_file = DEFAULT_OUTPUT
if (idx = ARGV.index("--output"))
  ARGV.delete_at(idx)
  output_file = ARGV.delete_at(idx)
end

def format_time(seconds)
  ms = seconds * 1000.0
  if seconds >= 1.0
    format("%.2fs", seconds)
  elsif ms < 0.1
    "<0.1ms"
  else
    format("%.1fms", ms)
  end
end

def format_speedup(slow, fast)
  return "-" if fast.zero?
  format("%.1fx", slow / fast)
end

# --- Collect benchmark data ---

repos = %w[mastodon discourse]
bench_data = {}
conform_data = {}

repos.each do |repo|
  bench_file = File.join(RESULTS_DIR, "#{repo}-bench.json")
  if File.exist?(bench_file)
    bench_data[repo] = JSON.parse(File.read(bench_file))
  end

  conform_file = File.join(RESULTS_DIR, "#{repo}-conformance.json")
  if File.exist?(conform_file)
    conform_data[repo] = JSON.parse(File.read(conform_file))
  end
end

if bench_data.empty? && conform_data.empty?
  abort "No results found in #{RESULTS_DIR}/. Run bench/bench.sh and/or bench/conform.sh first."
end

# Count covered cops
covered_file = File.join(RESULTS_DIR, "covered-cops.txt")
cop_count = if File.exist?(covered_file)
              File.readlines(covered_file).reject { |l| l.strip.empty? }.size
            end

# --- File counts (from bench repos) ---

def count_rb_files(repo_dir)
  Dir.glob(File.join(repo_dir, "**", "*.rb"))
    .reject { |f| f.include?("/vendor/") }
    .size
rescue
  nil
end

# --- Generate markdown ---

md = +""
md << "# turbocop Benchmark & Conformance Results\n\n"
md << "> Auto-generated by `bench/report.rb` on #{Time.now.utc.strftime("%Y-%m-%d %H:%M UTC")}\n\n"

platform = `uname -sm`.strip rescue "unknown"
md << "**Platform:** `#{platform}`\n"
md << "**turbocop cops:** #{cop_count}\n" if cop_count
md << "\n"

# --- Performance section ---

unless bench_data.empty?
  md << "## Performance\n\n"
  md << "| Repo | .rb files | turbocop (median) | rubocop (median) | Speedup |\n"
  md << "|------|-----------|-----------------|------------------|---------|\n"

  bench_data.each do |repo, data|
    results = data["results"]
    turbocop_result = results.find { |r| r["command"] == "turbocop" }
    rubocop_result = results.find { |r| r["command"] == "rubocop" }

    turbocop_median = turbocop_result&.dig("median") || 0
    rubocop_median = rubocop_result&.dig("median") || 0

    repo_dir = File.join(SCRIPT_DIR, "repos", repo)
    rb_count = count_rb_files(repo_dir)
    rb_str = rb_count ? rb_count.to_s.gsub(/(\d)(?=(\d{3})+$)/, '\\1,') : "?"

    speedup = format_speedup(rubocop_median, turbocop_median)
    md << "| #{repo} | #{rb_str} | **#{format_time(turbocop_median)}** | #{format_time(rubocop_median)} | **#{speedup}** |\n"
  end

  md << "\n"

  # Detailed stats
  md << "<details>\n<summary>Detailed timing (mean ± stddev, min..max)</summary>\n\n"
  bench_data.each do |repo, data|
    md << "### #{repo}\n\n"
    md << "| Tool | Mean | Stddev | Min | Max | Median |\n"
    md << "|------|------|--------|-----|-----|--------|\n"
    data["results"].each do |r|
      name = r["command"]
      bold = name == "turbocop"
      fmt = ->(v) { s = format_time(v); bold ? "**#{s}**" : s }
      md << "| #{bold ? "**#{name}**" : name} | #{fmt[r["mean"]]} | #{format_time(r["stddev"])} | #{fmt[r["min"]]} | #{fmt[r["max"]]} | #{fmt[r["median"]]} |\n"
    end
    md << "\n"
  end
  md << "</details>\n\n"
end

# --- Conformance section ---

unless conform_data.empty?
  md << "## Conformance\n\n"
  md << "Location-level comparison: file + line + cop_name. Only cops implemented by turbocop are compared.\n\n"
  md << "| Repo | turbocop | rubocop | Matches | FP (turbocop only) | FN (rubocop only) | Match rate |\n"
  md << "|------|--------|---------|---------|------------------|-------------------|------------|\n"

  conform_data.each do |repo, data|
    md << "| #{repo} | #{data["turbocop_count"]} | #{data["rubocop_count"]} | #{data["matches"]} | #{data["false_positives"]} | #{data["false_negatives"]} | **#{data["match_rate"]}%** |\n"
  end

  md << "\n"

  # Per-cop divergence tables (top 20 per repo)
  conform_data.each do |repo, data|
    per_cop = data["per_cop"] || {}
    divergent = per_cop.select { |_, v| v["fp"].to_i > 0 || v["fn"].to_i > 0 }
      .sort_by { |_, v| -(v["fp"].to_i + v["fn"].to_i) }
      .first(20)

    next if divergent.empty?

    md << "<details>\n<summary>Top divergent cops — #{repo} (#{divergent.size} shown)</summary>\n\n"
    md << "| Cop | Matches | FP | FN |\n"
    md << "|-----|--------:|---:|---:|\n"
    divergent.each do |cop, counts|
      md << "| #{cop} | #{counts["match"]} | #{counts["fp"]} | #{counts["fn"]} |\n"
    end
    md << "\n</details>\n\n"
  end
end

# --- Write ---

File.write(output_file, md)
puts "Wrote #{output_file}"
