pub mod ancestors_include;
pub mod array_semi_infinite_range_slice;
pub mod big_decimal_with_numeric_argument;
pub mod bind_call;
pub mod block_given_with_explicit_block;
pub mod caller;
pub mod case_when_splat;
pub mod casecmp;
pub mod chain_array_allocation;
pub mod compare_with_block;
pub mod concurrent_monotonic_time;
pub mod count;
pub mod delete_prefix;
pub mod delete_suffix;
pub mod detect;
pub mod double_start_end_with;
pub mod end_with;
pub mod flat_map;
pub mod inefficient_hash_search;
pub mod io_readlines;
pub mod map_compact;
pub mod map_method_chain;
pub mod method_object_as_block;
pub mod open_struct;
pub mod range_include;
pub mod redundant_block_call;
pub mod redundant_equality_comparison_block;
pub mod redundant_match;
pub mod redundant_merge;
pub mod redundant_sort_block;
pub mod redundant_split_regexp_argument;
pub mod redundant_string_chars;
pub mod regexp_match;
pub mod reverse_each;
pub mod reverse_first;
pub mod select_map;
pub mod size;
pub mod sort_reverse;
pub mod squeeze;
pub mod start_with;
pub mod string_include;
pub mod string_identifier_argument;
pub mod string_replacement;
pub mod sum;
pub mod times_map;
pub mod unfreeze_string;
pub mod uri_default_parser;

use super::registry::CopRegistry;

pub fn register_all(registry: &mut CopRegistry) {
    registry.register(Box::new(ancestors_include::AncestorsInclude));
    registry.register(Box::new(array_semi_infinite_range_slice::ArraySemiInfiniteRangeSlice));
    registry.register(Box::new(big_decimal_with_numeric_argument::BigDecimalWithNumericArgument));
    registry.register(Box::new(bind_call::BindCall));
    registry.register(Box::new(block_given_with_explicit_block::BlockGivenWithExplicitBlock));
    registry.register(Box::new(caller::Caller));
    registry.register(Box::new(case_when_splat::CaseWhenSplat));
    registry.register(Box::new(casecmp::Casecmp));
    registry.register(Box::new(chain_array_allocation::ChainArrayAllocation));
    registry.register(Box::new(compare_with_block::CompareWithBlock));
    registry.register(Box::new(concurrent_monotonic_time::ConcurrentMonotonicTime));
    registry.register(Box::new(count::Count));
    registry.register(Box::new(delete_prefix::DeletePrefix));
    registry.register(Box::new(delete_suffix::DeleteSuffix));
    registry.register(Box::new(detect::Detect));
    registry.register(Box::new(double_start_end_with::DoubleStartEndWith));
    registry.register(Box::new(end_with::EndWith));
    registry.register(Box::new(flat_map::FlatMap));
    registry.register(Box::new(inefficient_hash_search::InefficientHashSearch));
    registry.register(Box::new(io_readlines::IoReadlines));
    registry.register(Box::new(map_compact::MapCompact));
    registry.register(Box::new(map_method_chain::MapMethodChain));
    registry.register(Box::new(method_object_as_block::MethodObjectAsBlock));
    registry.register(Box::new(open_struct::OpenStruct));
    registry.register(Box::new(range_include::RangeInclude));
    registry.register(Box::new(redundant_block_call::RedundantBlockCall));
    registry.register(Box::new(redundant_equality_comparison_block::RedundantEqualityComparisonBlock));
    registry.register(Box::new(redundant_match::RedundantMatch));
    registry.register(Box::new(redundant_merge::RedundantMerge));
    registry.register(Box::new(redundant_sort_block::RedundantSortBlock));
    registry.register(Box::new(redundant_split_regexp_argument::RedundantSplitRegexpArgument));
    registry.register(Box::new(redundant_string_chars::RedundantStringChars));
    registry.register(Box::new(regexp_match::RegexpMatch));
    registry.register(Box::new(reverse_each::ReverseEach));
    registry.register(Box::new(reverse_first::ReverseFirst));
    registry.register(Box::new(select_map::SelectMap));
    registry.register(Box::new(size::Size));
    registry.register(Box::new(sort_reverse::SortReverse));
    registry.register(Box::new(squeeze::Squeeze));
    registry.register(Box::new(start_with::StartWith));
    registry.register(Box::new(string_identifier_argument::StringIdentifierArgument));
    registry.register(Box::new(string_include::StringInclude));
    registry.register(Box::new(string_replacement::StringReplacement));
    registry.register(Box::new(sum::Sum));
    registry.register(Box::new(times_map::TimesMap));
    registry.register(Box::new(unfreeze_string::UnfreezeString));
    registry.register(Box::new(uri_default_parser::UriDefaultParser));
}
