#!/usr/bin/env python3
"""Find corpus repos with diverse .rubocop.yml configurations.

Scans cloned corpus repos for non-default style configurations, style gem
inheritance, and other config diversity indicators. Outputs a curated list
for use with `check_cop.py --native-config --repos-file`.

Usage:
    python3 scripts/find_diverse_config_repos.py --min-styles 3
    python3 scripts/find_diverse_config_repos.py --output bench/corpus/diverse_config_repos.txt
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CORPUS_DIR = PROJECT_ROOT / "vendor" / "corpus"


def scan_repo_config(repo_dir: Path) -> dict:
    """Analyze a repo's .rubocop.yml for diversity indicators."""
    rubocop_yml = repo_dir / ".rubocop.yml"
    if not rubocop_yml.exists():
        return {}

    try:
        text = rubocop_yml.read_text(errors="replace")
    except OSError:
        return {}

    result: dict = {
        "enforced_styles": 0,
        "inherit_gem": [],
        "disabled_by_default": False,
        "inherit_from": [],
    }

    for line in text.splitlines():
        stripped = line.strip()

        # Count EnforcedStyle overrides
        if re.match(r"\s+Enforced\w+:", line):
            result["enforced_styles"] += 1

        # Detect inherit_gem
        m = re.match(r"\s*-?\s*([\w-]+):", stripped)
        if "inherit_gem:" in text and m:
            # Very rough detection
            pass

        if "inherit_gem:" in stripped or "inherit_gem :" in stripped:
            result["inherit_gem_detected"] = True

        if "DisabledByDefault: true" in stripped:
            result["disabled_by_default"] = True

        if "inherit_from:" in stripped:
            result["has_inherit_from"] = True

    # Look for common style gem references
    for gem in ["standard", "rubocop-shopify", "rubocop-airbnb", "rubocop-thoughtbot"]:
        if gem in text:
            result["inherit_gem"].append(gem)

    return result


def main():
    parser = argparse.ArgumentParser(description="Find repos with diverse rubocop configs")
    parser.add_argument("--min-styles", type=int, default=3,
                        help="Minimum non-default style overrides to include (default: 3)")
    parser.add_argument("--output", type=Path, default=None,
                        help="Write repo list to file")
    parser.add_argument("--corpus-dir", type=Path, default=CORPUS_DIR,
                        help="Corpus directory")
    parser.add_argument("--limit", type=int, default=50,
                        help="Maximum repos to output (default: 50)")
    args = parser.parse_args()

    corpus_dir = args.corpus_dir
    if not corpus_dir.exists():
        print(f"Corpus directory not found: {corpus_dir}", file=sys.stderr)
        print("Clone some repos first with check_cop.py --clone", file=sys.stderr)
        sys.exit(1)

    results = []
    for repo_dir in sorted(corpus_dir.iterdir()):
        if not repo_dir.is_dir():
            continue
        info = scan_repo_config(repo_dir)
        if not info:
            continue
        score = info.get("enforced_styles", 0)
        if info.get("inherit_gem"):
            score += 5 * len(info["inherit_gem"])
        if info.get("disabled_by_default"):
            score += 3
        if score >= args.min_styles:
            results.append((repo_dir.name, score, info))

    results.sort(key=lambda x: -x[1])
    results = results[:args.limit]

    lines = [
        "# Corpus repos with diverse .rubocop.yml configurations.",
        "# Generated by: python3 scripts/find_diverse_config_repos.py",
        f"# {len(results)} repos with >= {args.min_styles} style diversity score.",
        "#",
        "# Use with: python3 scripts/check_cop.py CopName --native-config --repos-file THIS_FILE",
        "",
    ]

    for repo_id, score, info in results:
        gems = ", ".join(info.get("inherit_gem", []))
        comment = f"# score={score}"
        if gems:
            comment += f" gems={gems}"
        if info.get("disabled_by_default"):
            comment += " DisabledByDefault"
        lines.append(f"{repo_id}  {comment}")

    output_text = "\n".join(lines) + "\n"

    if args.output:
        args.output.write_text(output_text)
        print(f"Wrote {len(results)} repos to {args.output}", file=sys.stderr)
    else:
        print(output_text)

    print(f"\nFound {len(results)} repos with style diversity >= {args.min_styles}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
