#!/usr/bin/env python3
"""Generate corpus-results.md from an existing corpus-results.json.

This is a lightweight alternative to re-running diff_results.py when
only the markdown needs to be regenerated (e.g. after patching variant
stats or merging include-gated results). It reads the JSON that
diff_results.py already produced and generates the markdown from it.

Usage:
    python3 bench/corpus/gen_corpus_md.py \
        --input corpus-results.json \
        --output corpus-results.md \
        --style-variant-results style-variant-results.json
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path


def fmt_pct(rate: float) -> str:
    return f"{math.floor(rate * 1000) / 10:.1f}%"


def _sanitize_for_md(s: str) -> str:
    return "".join(
        repr(c)[1:-1] if ord(c) < 0x20 and c not in '\n\t' else c
        for c in s
    )


def _format_example_md(ex) -> str:
    if isinstance(ex, dict):
        loc = ex.get("loc", "")
        msg = ex.get("msg", "")
        msg = _sanitize_for_md(msg)
        return f"{loc}  [{msg}]" if msg else loc
    return _sanitize_for_md(ex)


def generate_md(data: dict, variant_by_cop: dict[str, list[dict]]) -> str:
    """Generate corpus markdown from pre-computed JSON data."""
    summary = data["summary"]
    by_cop = data["by_cop"]
    by_department = data["by_department"]
    repo_results = data.get("by_repo", [])
    by_repo_cop = data.get("by_repo_cop", {})

    total_matches = summary["matches"]
    total_fp = summary["fp"]
    total_fn = summary["fn"]
    oracle_total = total_matches + total_fp + total_fn
    overall_rate = summary.get("overall_match_rate", total_matches / oracle_total if oracle_total > 0 else 1.0)
    repos_perfect = summary.get("repos_perfect", 0)
    repos_error = summary.get("repos_error", 0)
    registered_cops = summary.get("registered_cops", len(by_cop))
    perfect_cops = summary.get("perfect_cops", 0)
    diverging_cops_count = summary.get("diverging_cops", 0)
    inactive_cops = summary.get("inactive_cops", 0)
    total_files = summary.get("total_files_inspected", 0)
    total_files_dropped = summary.get("rubocop_files_dropped", 0)
    all_ids_count = summary.get("total_repos", 0)
    warning_repos = [r for r in repo_results if r.get("rubocop_files_dropped", 0) > 0]

    # Variant totals
    variant_total_matches = total_matches
    variant_total_fp = total_fp
    variant_total_fn = total_fn
    variant_dept_stats: dict[str, dict[str, int]] = {}
    for cop_name, variants in variant_by_cop.items():
        dept = cop_name.split("/")[0]
        if dept not in variant_dept_stats:
            variant_dept_stats[dept] = {"matches": 0, "fp": 0, "fn": 0}
        for v in variants:
            variant_total_matches += v["matches"]
            variant_total_fp += v["fp"]
            variant_total_fn += v["fn"]
            variant_dept_stats[dept]["matches"] += v["matches"]
            variant_dept_stats[dept]["fp"] += v["fp"]
            variant_dept_stats[dept]["fn"] += v["fn"]
    variant_oracle_total = variant_total_matches + variant_total_fp + variant_total_fn
    variant_overall_rate = variant_total_matches / variant_oracle_total if variant_oracle_total > 0 else 1.0

    md = []
    md.append("# Corpus Oracle Results")
    md.append("")
    md.append("> Auto-generated by the [corpus oracle workflow](../.github/workflows/corpus-oracle.yml).")
    md.append(f"> Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
    md.append("")
    md.append(f"Compares nitrocop against RuboCop on {all_ids_count:,} open-source Ruby repos.")
    md.append("Every offense is compared by file path, line number, and cop name.")
    md.append("")

    md.append("## Summary")
    md.append("")
    md.append("| Metric | Value |")
    md.append("|--------|------:|")
    md.append(f"| Repos | {all_ids_count} |")
    md.append(f"| Repos with 100% match | {repos_perfect} |")
    md.append(f"| Files inspected | {total_files:,} |")
    md.append(f"| Offenses compared | {oracle_total:,} |")
    md.append(f"| Matches (both agree) | {total_matches:,} |")
    md.append(f"| FP (nitrocop extra) | {total_fp:,} |")
    md.append(f"| FN (nitrocop missing) | {total_fn:,} |")
    md.append(f"| Registered cops | {registered_cops:,} |")
    md.append(f"| Cops with exact match | {perfect_cops:,} |")
    md.append(f"| Cops with divergence | {diverging_cops_count:,} |")
    md.append(f"| Cops with no corpus data | {inactive_cops:,} |")
    md.append(f"| **Match rate (default config)** | **{fmt_pct(overall_rate)}** |")
    if variant_by_cop:
        md.append(f"| **Match rate (all variants)** | **{fmt_pct(variant_overall_rate)}** |")
    if repos_error > 0 or warning_repos:
        md.append(f"| Repos with errors | {repos_error} |")
    if warning_repos:
        md.append(f"| Repos with RuboCop parser crashes | {len(warning_repos)} |")
        md.append(f"| RuboCop files dropped (parser crash) | {total_files_dropped:,} |")
    md.append("")

    # Department breakdown
    if by_department:
        md.append("## Department Breakdown")
        md.append("")
        if variant_by_cop:
            md.append("| Department | Total cops | Exact match | Diverging | No corpus data | Matches | FP | FN | Default variant % | All variants % |")
            md.append("|------------|-----------:|------------:|----------:|---------------:|--------:|---:|---:|---------:|---------------:|")
        else:
            md.append("| Department | Total cops | Exact match | Diverging | No corpus data | Matches | FP | FN | Match % |")
            md.append("|------------|-----------:|------------:|----------:|---------------:|--------:|---:|---:|--------:|")
        for d in by_department:
            total = d["matches"] + d["fp"] + d["fn"]
            pct = fmt_pct(d['match_rate']) if total > 0 else "N/A"
            row = (
                f"| {d['department']} | {d['cops']:,} | "
                f"{d['perfect_cops']:,} | {d['diverging_cops']:,} | {d['inactive_cops']:,} | "
                f"{d['matches']:,} | {d['fp']:,} | {d['fn']:,} | {pct}"
            )
            if variant_by_cop:
                vd = variant_dept_stats.get(d["department"], {"matches": 0, "fp": 0, "fn": 0})
                v_total = total + vd["matches"] + vd["fp"] + vd["fn"]
                v_matches = d["matches"] + vd["matches"]
                v_pct = fmt_pct(v_matches / v_total) if v_total > 0 else "N/A"
                row += f" | {v_pct} |"
            else:
                row += " |"
            md.append(row)
        md.append("")

    # Diverging cops
    ok_repos = [r for r in repo_results if r.get("status") == "ok"]
    err_repos = [r for r in repo_results if r.get("status") != "ok"]

    # Top divergence contributors
    multi_repo = all_ids_count > 1
    if multi_repo and by_repo_cop:
        repo_diverging_cops: dict[str, int] = {}
        repo_fp_cops: dict[str, int] = {}
        repo_fn_cops: dict[str, int] = {}
        for repo_id_key, cops in by_repo_cop.items():
            fp_cops = sum(1 for c in cops.values() if c.get("fp", 0) > 0)
            fn_cops = sum(1 for c in cops.values() if c.get("fn", 0) > 0)
            diverging = sum(1 for c in cops.values() if c.get("fp", 0) + c.get("fn", 0) > 0)
            if diverging > 0:
                repo_diverging_cops[repo_id_key] = diverging
                repo_fp_cops[repo_id_key] = fp_cops
                repo_fn_cops[repo_id_key] = fn_cops

        if repo_diverging_cops:
            top = sorted(repo_diverging_cops.items(), key=lambda x: x[1], reverse=True)[:20]
            md.append("## Top Divergence Contributors (repos with most diverging cops)")
            md.append("")
            md.append("| Repo | Diverging Cops | FP Cops | FN Cops | Total FP | Total FN |")
            md.append("|------|---------------:|--------:|--------:|---------:|---------:|")
            for repo_id_key, div_count in top:
                r = next((x for x in ok_repos if x["repo"] == repo_id_key), None)
                total_fp_count = r["fp"] if r else 0
                total_fn_count = r["fn"] if r else 0
                md.append(
                    f"| {repo_id_key} | {div_count} | "
                    f"{repo_fp_cops.get(repo_id_key, 0)} | {repo_fn_cops.get(repo_id_key, 0)} | "
                    f"{total_fp_count:,} | {total_fn_count:,} |"
                )
            md.append("")

    # RuboCop warnings
    warn_and_err = warning_repos + err_repos
    if warn_and_err:
        md.append("## RuboCop Warnings")
        md.append("")
        md.append(f"{len(warn_and_err)} repos had RuboCop issues (parser crashes or errors).")
        md.append("")
        md.append("| Repo | Issue | Files Dropped | Error |")
        md.append("|------|-------|--------------|-------|")
        for r in warning_repos:
            dropped = r.get("rubocop_files_dropped", 0)
            err = r.get("rubocop_error", "")
            err_cell = f"`{err}`" if err else ""
            md.append(f"| {r['repo']} | parser crash | {dropped:,} | {err_cell} |")
        for r in err_repos:
            err = r.get("error_message", "")
            err_cell = f"`{err}`" if err else ""
            md.append(f"| {r['repo']} | {r['status']} | all | {err_cell} |")
        md.append("")

    # Diverging cops with variant rows
    diverging = [c for c in by_cop if c.get("diverging")]
    perfect_cop_list = [c for c in by_cop if c.get("perfect_match")]

    variant_only_diverging = []
    if variant_by_cop:
        default_diverging_names = {c["cop"] for c in diverging}
        for cop_name, variants in sorted(variant_by_cop.items()):
            if cop_name not in default_diverging_names:
                if any(v["fp"] + v["fn"] > 0 for v in variants):
                    cop_entry = next((c for c in by_cop if c["cop"] == cop_name), None)
                    if cop_entry:
                        variant_only_diverging.append(cop_entry)

    all_diverging = diverging + variant_only_diverging
    if all_diverging:
        md.append("## Diverging Cops")
        md.append("")
        md.append(
            f"{len(diverging)} cops diverge from RuboCop on the corpus (default config). "
            f"{len(perfect_cop_list)} cops match RuboCop exactly. "
            f"{inactive_cops} cops have no corpus data."
        )
        if variant_only_diverging:
            md.append(
                f" {len(variant_only_diverging)} additional cops diverge only in non-default style variants."
            )
        md.append("")
        md.append("| Cop | Matches | FP | FN | Match % |")
        md.append("|-----|--------:|---:|---:|--------:|")
        for c in diverging:
            total = c["matches"] + c["fp"] + c["fn"]
            pct = fmt_pct(c['match_rate']) if total > 0 else "N/A"
            if c["cop"] in variant_by_cop:
                md.append(f"| {c['cop']} (default) | {c['matches']:,} | {c['fp']:,} | {c['fn']:,} | {pct} |")
                for v in variant_by_cop[c["cop"]]:
                    v_total = v["matches"] + v["fp"] + v["fn"]
                    if v_total == 0:
                        continue
                    v_pct = fmt_pct(v["matches"] / v_total)
                    md.append(f"| ↳ {c['cop']} ({v['style_label']}) | {v['matches']:,} | {v['fp']:,} | {v['fn']:,} | {v_pct} |")
            else:
                md.append(f"| {c['cop']} | {c['matches']:,} | {c['fp']:,} | {c['fn']:,} | {pct} |")

        if variant_only_diverging:
            md.append("")
            md.append("**Variant-only divergence** (perfect in default config, diverge in non-default styles):")
            md.append("")
            md.append("| Cop | Matches | FP | FN | Match % |")
            md.append("|-----|--------:|---:|---:|--------:|")
            for c in sorted(variant_only_diverging, key=lambda x: sum(v["fp"] + v["fn"] for v in variant_by_cop.get(x["cop"], [])), reverse=True):
                total = c["matches"] + c["fp"] + c["fn"]
                pct = fmt_pct(c['match_rate']) if total > 0 else "N/A"
                md.append(f"| {c['cop']} (default) | {c['matches']:,} | {c['fp']:,} | {c['fn']:,} | {pct} |")
                for v in variant_by_cop.get(c["cop"], []):
                    v_total = v["matches"] + v["fp"] + v["fn"]
                    v_pct = fmt_pct(v["matches"] / v_total) if v_total > 0 else "N/A"
                    if v["fp"] + v["fn"] > 0:
                        md.append(f"| ↳ {c['cop']} ({v['style_label']}) | {v['matches']:,} | {v['fp']:,} | {v['fn']:,} | {v_pct} |")
        md.append("")

        # Detail sections
        MD_EXAMPLE_LIMIT = 3
        for c in diverging:
            fp_list = c.get("fp_examples", [])
            fn_list = c.get("fn_examples", [])
            if not fp_list and not fn_list:
                continue
            total = c["matches"] + c["fp"] + c["fn"]
            pct = fmt_pct(c['match_rate']) if total > 0 else "N/A"
            md.append("<details>")
            md.append(f"<summary><strong>{c['cop']}</strong> — {c['matches']:,} matches, {c['fp']:,} FP, {c['fn']:,} FN ({pct})</summary>")
            md.append("")
            if fp_list:
                md.append("**False positives** (nitrocop reports, RuboCop does not):")
                md.append("")
                for ex in fp_list[:MD_EXAMPLE_LIMIT]:
                    md.append(f"- `{_format_example_md(ex)}`")
                if len(fp_list) > MD_EXAMPLE_LIMIT:
                    md.append(f"- ... and {len(fp_list) - MD_EXAMPLE_LIMIT:,} more (see corpus-results.json for full list)")
                md.append("")
            if fn_list:
                md.append("**False negatives** (RuboCop reports, nitrocop does not):")
                md.append("")
                for ex in fn_list[:MD_EXAMPLE_LIMIT]:
                    md.append(f"- `{_format_example_md(ex)}`")
                if len(fn_list) > MD_EXAMPLE_LIMIT:
                    md.append(f"- ... and {len(fn_list) - MD_EXAMPLE_LIMIT:,} more (see corpus-results.json for full list)")
                md.append("")
            md.append("</details>")
            md.append("")

    # Per-repo table
    md.append("## Per-Repo Results")
    md.append("")
    md.append(f"{len(ok_repos)} repos completed successfully, {len(err_repos)} had errors.")
    md.append("")
    md.append("| Repo | Files | Match Rate | Matches | FP | FN |")
    md.append("|------|------:|----------:|--------:|---:|---:|")
    for r in sorted(ok_repos, key=lambda x: x.get("match_rate", 0)):
        files = r.get("files_inspected", 0)
        rate = fmt_pct(r['match_rate'])
        md.append(f"| {r['repo']} | {files:,} | {rate} | {r['matches']:,} | {r['fp']:,} | {r['fn']:,} |")
    md.append("")

    if err_repos:
        md.append("<details>")
        md.append(f"<summary>Repos with errors ({len(err_repos)})</summary>")
        md.append("")
        md.append("| Repo | Status | Error |")
        md.append("|------|--------|-------|")
        for r in err_repos:
            err = r.get("error_message", "")
            err_cell = f"`{err}`" if err else ""
            md.append(f"| {r['repo']} | {r['status']} | {err_cell} |")
        md.append("")
        md.append("</details>")
        md.append("")

    # Perfect cops
    if perfect_cop_list:
        md.append("<details>")
        md.append(f"<summary>Perfect cops ({len(perfect_cop_list)} cops with 100% match rate)</summary>")
        md.append("")
        md.append("| Cop | Matches |")
        md.append("|-----|--------:|")
        for c in sorted(perfect_cop_list, key=lambda x: x["matches"], reverse=True):
            md.append(f"| {c['cop']} | {c['matches']:,} |")
        md.append("")
        md.append("</details>")
        md.append("")

    return "\n".join(md) + "\n"


def load_variant_by_cop(path: Path) -> dict[str, list[dict]]:
    """Load variant results into {cop_name: [{style_label, matches, fp, fn}]}."""
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return {}
    result: dict[str, list[dict]] = {}
    for batch in data.get("batches", []):
        for cop_entry in batch.get("by_cop", []):
            cop_name = cop_entry.get("cop", "")
            if cop_name:
                result.setdefault(cop_name, []).append({
                    "style_label": cop_entry.get("style_label", batch.get("name", "?")),
                    "matches": cop_entry.get("matches", 0),
                    "fp": cop_entry.get("fp", 0),
                    "fn": cop_entry.get("fn", 0),
                })
    return result


def main():
    parser = argparse.ArgumentParser(
        description="Generate corpus-results.md from corpus-results.json")
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--style-variant-results", type=Path, default=None)
    args = parser.parse_args()

    data = json.loads(args.input.read_text())
    variant_by_cop = {}
    if args.style_variant_results:
        variant_by_cop = load_variant_by_cop(args.style_variant_results)

    md = generate_md(data, variant_by_cop)
    args.output.write_text(md)
    print(f"Generated {args.output} ({len(md):,} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
