#!/usr/bin/env python3
"""Generate variant batch configs from vendor defaults for corpus oracle runs.

Groups all (cop, style) variants into batches where each batch overrides
~80-100 cops simultaneously. Batch 1 sets each cop to its 2nd supported
style, batch 2 to the 3rd, etc. Most cops have 2-3 styles, so batch 1
covers all configurable cops and batches 2-3 cover progressively fewer.

Usage:
    python3 bench/corpus/gen_variant_batches.py --output-dir bench/corpus/variant_batches/
    python3 bench/corpus/gen_variant_batches.py --dry-run
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
from corpus_stress import VENDOR_CONFIGS, parse_enforced_styles  # noqa: E402

# Relative to the variant_batches/ subdirectory where generated configs live.
# RuboCop resolves inherit_from relative to the config file's directory.
BASELINE_PATH = "../baseline_rubocop.yml"


def generate_batches(output_dir: Path, *, dry_run: bool = False) -> int:
    """Generate variant_batch_{n}.yml files.

    Returns number of batches created.
    """
    all_styles: list[dict] = []
    for config_path, _plugin in VENDOR_CONFIGS:
        full_path = str(PROJECT_ROOT / config_path)
        all_styles.extend(parse_enforced_styles(full_path))

    # Find maximum number of alternatives across all styles
    max_alts = max((len(s["alternatives"]) for s in all_styles), default=0)
    if max_alts == 0:
        print("No style alternatives found in vendor configs.", file=sys.stderr)
        return 0

    # Group by cop for multi-key cops
    by_cop: dict[str, list[dict]] = {}
    for s in all_styles:
        by_cop.setdefault(s["cop"], []).append(s)

    batches_written = 0
    for batch_idx in range(max_alts):
        # Collect cops that have an alternative at this index
        entries: list[tuple[str, str, str, str]] = []  # (cop, key, value, default)
        for cop in sorted(by_cop.keys()):
            for s in by_cop[cop]:
                if batch_idx < len(s["alternatives"]):
                    alt = s["alternatives"][batch_idx]
                    entries.append((cop, s["key"], alt, s["default"]))

        if not entries:
            continue

        # Group entries by cop for YAML output
        cop_entries: dict[str, list[tuple[str, str, str]]] = {}
        for cop, key, value, default in entries:
            cop_entries.setdefault(cop, []).append((key, value, default))

        lines = [
            f"# Auto-generated variant batch {batch_idx + 1}:",
            f"# Each cop set to alternative style #{batch_idx + 1}.",
            f"# {len(cop_entries)} cops, {len(entries)} style overrides.",
            "# Generated by: python3 bench/corpus/gen_variant_batches.py",
            "",
            f"inherit_from: {BASELINE_PATH}",
            "",
        ]

        for cop in sorted(cop_entries.keys()):
            lines.append(f"{cop}:")
            for key, value, default in cop_entries[cop]:
                lines.append(f"  {key}: {value}  # default: {default}")
            lines.append("")

        content = "\n".join(lines) + "\n"
        filename = f"variant_batch_{batch_idx + 1}.yml"

        if dry_run:
            print(f"--- {filename} ({len(cop_entries)} cops, {len(entries)} overrides) ---")
            # Show first 5 cops as preview
            for line in content.splitlines()[:20]:
                print(f"  {line}")
            if len(content.splitlines()) > 20:
                print(f"  ... ({len(content.splitlines()) - 20} more lines)")
            print()
        else:
            output_dir.mkdir(parents=True, exist_ok=True)
            (output_dir / filename).write_text(content)
            print(f"Wrote {output_dir / filename} "
                  f"({len(cop_entries)} cops, {len(entries)} overrides)",
                  file=sys.stderr)

        batches_written += 1

    return batches_written


def main():
    parser = argparse.ArgumentParser(
        description="Generate variant batch configs from vendor defaults")
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parent / "variant_batches",
                        help="Output directory for batch configs")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview without writing files")
    args = parser.parse_args()

    n = generate_batches(args.output_dir, dry_run=args.dry_run)
    print(f"\n{n} variant batch(es) generated.", file=sys.stderr)


if __name__ == "__main__":
    main()
