pub mod and_or;
pub mod block_delimiters;
pub mod class_and_module_children;
pub mod colon_method_call;
pub mod def_with_parentheses;
pub mod documentation;
pub mod double_negation;
pub mod empty_method;
pub mod explicit_block_argument;
pub mod frozen_string_literal_comment;
pub mod global_vars;
pub mod hash_syntax;
pub mod hash_transform_keys;
pub mod hash_transform_values;
pub mod if_unless_modifier;
pub mod lambda;
pub mod method_call_with_args_parentheses;
pub mod method_def_parentheses;
pub mod mutable_constant;
pub mod negated_if;
pub mod negated_unless;
pub mod negated_while;
pub mod not;
pub mod numeric_literals;
pub mod open_struct_use;
pub mod parentheses_around_condition;
pub mod proc;
pub mod raise_args;
pub mod redundant_begin;
pub mod redundant_condition;
pub mod redundant_exception;
pub mod redundant_freeze;
pub mod redundant_interpolation;
pub mod redundant_percent_q;
pub mod redundant_return;
pub mod redundant_self;
pub mod rescue_modifier;
pub mod rescue_standard_error;
pub mod semicolon;
pub mod signal_exception;
pub mod single_line_methods;
pub mod special_global_vars;
pub mod stabby_lambda_parentheses;
pub mod string_literals;
pub mod symbol_array;
pub mod symbol_literal;
pub mod tab;
pub mod ternary_parentheses;
pub mod trivial_accessors;
pub mod trailing_comma_in_arguments;
pub mod trailing_comma_in_array_literal;
pub mod trailing_comma_in_hash_literal;
pub mod unless_else;
pub mod when_then;
pub mod word_array;
pub mod yoda_condition;

use super::registry::CopRegistry;

pub fn register_all(registry: &mut CopRegistry) {
    registry.register(Box::new(
        frozen_string_literal_comment::FrozenStringLiteralComment,
    ));
    registry.register(Box::new(tab::Tab));
    registry.register(Box::new(string_literals::StringLiterals));
    registry.register(Box::new(redundant_return::RedundantReturn));
    registry.register(Box::new(numeric_literals::NumericLiterals));
    registry.register(Box::new(semicolon::Semicolon));
    registry.register(Box::new(empty_method::EmptyMethod));
    registry.register(Box::new(negated_if::NegatedIf));
    registry.register(Box::new(negated_while::NegatedWhile));
    registry.register(Box::new(parentheses_around_condition::ParenthesesAroundCondition));
    registry.register(Box::new(if_unless_modifier::IfUnlessModifier));
    registry.register(Box::new(word_array::WordArray));
    registry.register(Box::new(symbol_array::SymbolArray));
    registry.register(Box::new(trailing_comma_in_arguments::TrailingCommaInArguments));
    registry.register(Box::new(trailing_comma_in_array_literal::TrailingCommaInArrayLiteral));
    registry.register(Box::new(trailing_comma_in_hash_literal::TrailingCommaInHashLiteral));
    registry.register(Box::new(class_and_module_children::ClassAndModuleChildren));
    registry.register(Box::new(ternary_parentheses::TernaryParentheses));
    registry.register(Box::new(documentation::Documentation));
    registry.register(Box::new(lambda::Lambda));
    registry.register(Box::new(self::proc::Proc));
    registry.register(Box::new(raise_args::RaiseArgs));
    registry.register(Box::new(rescue_modifier::RescueModifier));
    registry.register(Box::new(rescue_standard_error::RescueStandardError));
    registry.register(Box::new(signal_exception::SignalException));
    registry.register(Box::new(single_line_methods::SingleLineMethods));
    registry.register(Box::new(special_global_vars::SpecialGlobalVars));
    registry.register(Box::new(stabby_lambda_parentheses::StabbyLambdaParentheses));
    registry.register(Box::new(yoda_condition::YodaCondition));
    registry.register(Box::new(hash_syntax::HashSyntax));
    registry.register(Box::new(method_call_with_args_parentheses::MethodCallWithArgsParentheses));
    registry.register(Box::new(and_or::AndOr));
    registry.register(Box::new(method_def_parentheses::MethodDefParentheses));
    registry.register(Box::new(def_with_parentheses::DefWithParentheses));
    registry.register(Box::new(unless_else::UnlessElse));
    registry.register(Box::new(negated_unless::NegatedUnless));
    registry.register(Box::new(colon_method_call::ColonMethodCall));
    registry.register(Box::new(not::Not));
    registry.register(Box::new(redundant_freeze::RedundantFreeze));
    registry.register(Box::new(redundant_percent_q::RedundantPercentQ));
    registry.register(Box::new(redundant_exception::RedundantException));
    registry.register(Box::new(mutable_constant::MutableConstant));
    registry.register(Box::new(global_vars::GlobalVars));
    registry.register(Box::new(open_struct_use::OpenStructUse));
    registry.register(Box::new(symbol_literal::SymbolLiteral));
    registry.register(Box::new(when_then::WhenThen));
    registry.register(Box::new(redundant_condition::RedundantCondition));
    registry.register(Box::new(redundant_begin::RedundantBegin));
    registry.register(Box::new(redundant_self::RedundantSelf));
    registry.register(Box::new(redundant_interpolation::RedundantInterpolation));
    registry.register(Box::new(trivial_accessors::TrivialAccessors));
    registry.register(Box::new(explicit_block_argument::ExplicitBlockArgument));
    registry.register(Box::new(block_delimiters::BlockDelimiters));
    registry.register(Box::new(double_negation::DoubleNegation));
    registry.register(Box::new(hash_transform_keys::HashTransformKeys));
    registry.register(Box::new(hash_transform_values::HashTransformValues));
}
