pub mod alias;
pub mod and_or;
pub mod array_join;
pub mod attr;
pub mod bare_percent_literals;
pub mod begin_block;
pub mod block_comments;
pub mod block_delimiters;
pub mod case_equality;
pub mod character_literal;
pub mod class_and_module_children;
pub mod class_check;
pub mod class_equality_comparison;
pub mod class_methods;
pub mod class_vars;
pub mod colon_method_call;
pub mod colon_method_definition;
pub mod command_literal;
pub mod comment_annotation;
pub mod commented_keyword;
pub mod data_inheritance;
pub mod def_with_parentheses;
pub mod documentation;
pub mod double_negation;
pub mod each_for_simple_loop;
pub mod empty_block_parameter;
pub mod empty_case_condition;
pub mod empty_else;
pub mod empty_lambda_parameter;
pub mod empty_literal;
pub mod empty_method;
pub mod encoding;
pub mod end_block;
pub mod env_home;
pub mod even_odd;
pub mod expand_path_arguments;
pub mod explicit_block_argument;
pub mod for_cop;
pub mod frozen_string_literal_comment;
pub mod global_std_stream;
pub mod global_vars;
pub mod guard_clause;
pub mod hash_syntax;
pub mod hash_transform_keys;
pub mod hash_transform_values;
pub mod if_unless_modifier;
pub mod if_unless_modifier_of_if_unless;
pub mod if_with_boolean_literal_branches;
pub mod if_with_semicolon;
pub mod infinite_loop;
pub mod lambda;
pub mod lambda_call;
pub mod method_call_with_args_parentheses;
pub mod method_called_on_do_end_block;
pub mod method_def_parentheses;
pub mod min_max;
pub mod missing_respond_to_missing;
pub mod multiline_block_chain;
pub mod multiline_if_modifier;
pub mod multiline_if_then;
pub mod multiline_memoization;
pub mod multiline_method_signature;
pub mod multiline_ternary_operator;
pub mod multiline_when_then;
pub mod mutable_constant;
pub mod negated_if;
pub mod negated_unless;
pub mod negated_while;
pub mod nested_file_dirname;
pub mod nested_modifier;
pub mod nested_ternary_operator;
pub mod nil_comparison;
pub mod nil_lambda;
pub mod non_nil_check;
pub mod not;
pub mod numeric_literal_prefix;
pub mod numeric_literals;
pub mod numeric_predicate;
pub mod object_then;
pub mod one_class_per_file;
pub mod one_line_conditional;
pub mod open_struct_use;
pub mod optional_boolean_parameter;
pub mod or_assignment;
pub mod parentheses_around_condition;
pub mod preferred_hash_methods;
pub mod proc;
pub mod raise_args;
pub mod redundant_begin;
pub mod redundant_condition;
pub mod redundant_conditional;
pub mod redundant_current_directory_in_path;
pub mod redundant_exception;
pub mod redundant_file_extension_in_require;
pub mod redundant_freeze;
pub mod redundant_interpolation;
pub mod redundant_percent_q;
pub mod redundant_return;
pub mod redundant_self;
pub mod redundant_sort;
pub mod redundant_sort_by;
pub mod rescue_modifier;
pub mod rescue_standard_error;
pub mod safe_navigation;
pub mod sample;
pub mod select_by_regexp;
pub mod self_assignment;
pub mod semicolon;
pub mod send;
pub mod signal_exception;
pub mod single_argument_dig;
pub mod single_line_methods;
pub mod slicing_with_range;
pub mod special_global_vars;
pub mod stabby_lambda_parentheses;
pub mod stderr_puts;
pub mod string_chars;
pub mod string_concatenation;
pub mod string_literals;
pub mod strip;
pub mod struct_inheritance;
pub mod symbol_array;
pub mod symbol_literal;
pub mod tab;
pub mod ternary_parentheses;
pub mod trailing_body_on_class;
pub mod trailing_body_on_method_definition;
pub mod trailing_body_on_module;
pub mod trailing_comma_in_arguments;
pub mod trailing_comma_in_array_literal;
pub mod trailing_comma_in_hash_literal;
pub mod trailing_method_end_statement;
pub mod trivial_accessors;
pub mod unless_else;
pub mod unpack_first;
pub mod when_then;
pub mod while_until_do;
pub mod word_array;
pub mod yoda_condition;
pub mod zero_length_predicate;

use super::registry::CopRegistry;

pub fn register_all(registry: &mut CopRegistry) {
    registry.register(Box::new(
        frozen_string_literal_comment::FrozenStringLiteralComment,
    ));
    registry.register(Box::new(tab::Tab));
    registry.register(Box::new(string_literals::StringLiterals));
    registry.register(Box::new(redundant_return::RedundantReturn));
    registry.register(Box::new(numeric_literals::NumericLiterals));
    registry.register(Box::new(semicolon::Semicolon));
    registry.register(Box::new(empty_method::EmptyMethod));
    registry.register(Box::new(negated_if::NegatedIf));
    registry.register(Box::new(negated_while::NegatedWhile));
    registry.register(Box::new(parentheses_around_condition::ParenthesesAroundCondition));
    registry.register(Box::new(if_unless_modifier::IfUnlessModifier));
    registry.register(Box::new(word_array::WordArray));
    registry.register(Box::new(symbol_array::SymbolArray));
    registry.register(Box::new(trailing_comma_in_arguments::TrailingCommaInArguments));
    registry.register(Box::new(trailing_comma_in_array_literal::TrailingCommaInArrayLiteral));
    registry.register(Box::new(trailing_comma_in_hash_literal::TrailingCommaInHashLiteral));
    registry.register(Box::new(class_and_module_children::ClassAndModuleChildren));
    registry.register(Box::new(ternary_parentheses::TernaryParentheses));
    registry.register(Box::new(documentation::Documentation));
    registry.register(Box::new(lambda::Lambda));
    registry.register(Box::new(self::proc::Proc));
    registry.register(Box::new(raise_args::RaiseArgs));
    registry.register(Box::new(rescue_modifier::RescueModifier));
    registry.register(Box::new(rescue_standard_error::RescueStandardError));
    registry.register(Box::new(signal_exception::SignalException));
    registry.register(Box::new(single_line_methods::SingleLineMethods));
    registry.register(Box::new(special_global_vars::SpecialGlobalVars));
    registry.register(Box::new(stabby_lambda_parentheses::StabbyLambdaParentheses));
    registry.register(Box::new(yoda_condition::YodaCondition));
    registry.register(Box::new(hash_syntax::HashSyntax));
    registry.register(Box::new(method_call_with_args_parentheses::MethodCallWithArgsParentheses));
    registry.register(Box::new(and_or::AndOr));
    registry.register(Box::new(class_vars::ClassVars));
    registry.register(Box::new(method_def_parentheses::MethodDefParentheses));
    registry.register(Box::new(def_with_parentheses::DefWithParentheses));
    registry.register(Box::new(unless_else::UnlessElse));
    registry.register(Box::new(negated_unless::NegatedUnless));
    registry.register(Box::new(colon_method_call::ColonMethodCall));
    registry.register(Box::new(not::Not));
    registry.register(Box::new(redundant_freeze::RedundantFreeze));
    registry.register(Box::new(redundant_percent_q::RedundantPercentQ));
    registry.register(Box::new(redundant_exception::RedundantException));
    registry.register(Box::new(mutable_constant::MutableConstant));
    registry.register(Box::new(global_vars::GlobalVars));
    registry.register(Box::new(open_struct_use::OpenStructUse));
    registry.register(Box::new(symbol_literal::SymbolLiteral));
    registry.register(Box::new(when_then::WhenThen));
    registry.register(Box::new(redundant_condition::RedundantCondition));
    registry.register(Box::new(redundant_begin::RedundantBegin));
    registry.register(Box::new(redundant_self::RedundantSelf));
    registry.register(Box::new(redundant_interpolation::RedundantInterpolation));
    registry.register(Box::new(trivial_accessors::TrivialAccessors));
    registry.register(Box::new(explicit_block_argument::ExplicitBlockArgument));
    registry.register(Box::new(block_delimiters::BlockDelimiters));
    registry.register(Box::new(double_negation::DoubleNegation));
    registry.register(Box::new(hash_transform_keys::HashTransformKeys));
    registry.register(Box::new(hash_transform_values::HashTransformValues));
    registry.register(Box::new(non_nil_check::NonNilCheck));
    registry.register(Box::new(nil_lambda::NilLambda));
    registry.register(Box::new(or_assignment::OrAssignment));
    registry.register(Box::new(self_assignment::SelfAssignment));
    registry.register(Box::new(zero_length_predicate::ZeroLengthPredicate));
    registry.register(Box::new(strip::Strip));
    registry.register(Box::new(numeric_literal_prefix::NumericLiteralPrefix));
    registry.register(Box::new(numeric_predicate::NumericPredicate));
    registry.register(Box::new(unpack_first::UnpackFirst));
    registry.register(Box::new(redundant_sort::RedundantSort));
    registry.register(Box::new(object_then::ObjectThen));
    registry.register(Box::new(safe_navigation::SafeNavigation));
    registry.register(Box::new(preferred_hash_methods::PreferredHashMethods));
    registry.register(Box::new(sample::Sample));
    registry.register(Box::new(redundant_conditional::RedundantConditional));
    registry.register(Box::new(slicing_with_range::SlicingWithRange));
    registry.register(Box::new(string_concatenation::StringConcatenation));
    registry.register(Box::new(single_argument_dig::SingleArgumentDig));
    registry.register(Box::new(select_by_regexp::SelectByRegexp));
    registry.register(Box::new(redundant_file_extension_in_require::RedundantFileExtensionInRequire));
    registry.register(Box::new(guard_clause::GuardClause));
    registry.register(Box::new(one_class_per_file::OneClassPerFile));
    registry.register(Box::new(optional_boolean_parameter::OptionalBooleanParameter));
    registry.register(Box::new(commented_keyword::CommentedKeyword));
    registry.register(Box::new(encoding::Encoding));
    registry.register(Box::new(multiline_if_then::MultilineIfThen));
    registry.register(Box::new(multiline_when_then::MultilineWhenThen));
    registry.register(Box::new(multiline_if_modifier::MultilineIfModifier));
    registry.register(Box::new(empty_case_condition::EmptyCaseCondition));
    registry.register(Box::new(missing_respond_to_missing::MissingRespondToMissing));
    registry.register(Box::new(if_with_boolean_literal_branches::IfWithBooleanLiteralBranches));
    registry.register(Box::new(expand_path_arguments::ExpandPathArguments));
    registry.register(Box::new(multiline_memoization::MultilineMemoization));
    // Previously unregistered cops
    registry.register(Box::new(self::alias::Alias));
    registry.register(Box::new(array_join::ArrayJoin));
    registry.register(Box::new(attr::Attr));
    registry.register(Box::new(bare_percent_literals::BarePercentLiterals));
    registry.register(Box::new(begin_block::BeginBlock));
    registry.register(Box::new(block_comments::BlockComments));
    registry.register(Box::new(case_equality::CaseEquality));
    registry.register(Box::new(character_literal::CharacterLiteral));
    registry.register(Box::new(class_check::ClassCheck));
    registry.register(Box::new(class_equality_comparison::ClassEqualityComparison));
    registry.register(Box::new(class_methods::ClassMethods));
    registry.register(Box::new(colon_method_definition::ColonMethodDefinition));
    registry.register(Box::new(command_literal::CommandLiteral));
    registry.register(Box::new(comment_annotation::CommentAnnotation));
    registry.register(Box::new(each_for_simple_loop::EachForSimpleLoop));
    registry.register(Box::new(empty_block_parameter::EmptyBlockParameter));
    registry.register(Box::new(empty_else::EmptyElse));
    registry.register(Box::new(empty_lambda_parameter::EmptyLambdaParameter));
    registry.register(Box::new(empty_literal::EmptyLiteral));
    registry.register(Box::new(end_block::EndBlock));
    registry.register(Box::new(even_odd::EvenOdd));
    registry.register(Box::new(for_cop::ForCop));
    registry.register(Box::new(infinite_loop::InfiniteLoop));
    registry.register(Box::new(nil_comparison::NilComparison));
    // New cops
    registry.register(Box::new(stderr_puts::StderrPuts));
    registry.register(Box::new(string_chars::StringChars));
    registry.register(Box::new(nested_ternary_operator::NestedTernaryOperator));
    registry.register(Box::new(while_until_do::WhileUntilDo));
    registry.register(Box::new(multiline_ternary_operator::MultilineTernaryOperator));
    registry.register(Box::new(global_std_stream::GlobalStdStream));
    registry.register(Box::new(struct_inheritance::StructInheritance));
    registry.register(Box::new(data_inheritance::DataInheritance));
    registry.register(Box::new(lambda_call::LambdaCall));
    registry.register(Box::new(if_with_semicolon::IfWithSemicolon));
    registry.register(Box::new(redundant_sort_by::RedundantSortBy));
    registry.register(Box::new(trailing_body_on_class::TrailingBodyOnClass));
    registry.register(Box::new(trailing_body_on_module::TrailingBodyOnModule));
    registry.register(Box::new(trailing_body_on_method_definition::TrailingBodyOnMethodDefinition));
    registry.register(Box::new(trailing_method_end_statement::TrailingMethodEndStatement));
    registry.register(Box::new(one_line_conditional::OneLineConditional));
    registry.register(Box::new(if_unless_modifier_of_if_unless::IfUnlessModifierOfIfUnless));
    registry.register(Box::new(multiline_method_signature::MultilineMethodSignature));
    registry.register(Box::new(multiline_block_chain::MultilineBlockChain));
    registry.register(Box::new(method_called_on_do_end_block::MethodCalledOnDoEndBlock));
    registry.register(Box::new(env_home::EnvHome));
    registry.register(Box::new(redundant_current_directory_in_path::RedundantCurrentDirectoryInPath));
    registry.register(Box::new(nested_modifier::NestedModifier));
    registry.register(Box::new(self::send::Send));
    registry.register(Box::new(nested_file_dirname::NestedFileDirname));
    registry.register(Box::new(min_max::MinMax));
}
