# BEGIN generated by rake update, do not modify
# https://raw.githubusercontent.com/blowmage/minitest-rg/master/LICENSE
=begin
Copyright (c) 2023 Mike Moore

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:
=end
# END generated by rake update, do not modify

# frozen_string_literal: true

puts "hello"
x = 1
y = 2
z = 3
a = 4
b = 5
